version: "3.5"

services:
    postgres:
        image: postgres:12.7-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-4978}
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin:/root/.pgadmin
        networks:
            - postgres
            - public
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=public"
            - "traefik.http.routers.pgadmin.entrypoints=web"
            - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
            - "traefik.http.routers.pgadmin.service=pgadmin"
            - "traefik.http.services.pgadmin.loadbalancer.server.port=${PGADMIN_LISTEN_PORT:-4978}"

networks:
    public:
        external: true
    postgres:
        external: true

volumes:
    postgres:
    pgadmin:
